services:
  - type: web
    name: mutual-fund-comparison
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PORT
        value: 10000